ID:
  client_id:
  endpoint_id:
  user_id:
LastJobName:
ModelList:
  ModelDLC : ""
TemporaryFolder:
host:
port: 22
redirect_url: https://auth.globus.org/v2/web/auth-code
scopes: urn:globus:auth:scope:transfer.api.globus.org:all[*https://auth.globus.org/scopes/ENDPOINT_ID/data_access]
script_folder:
ssh_key_path:
username: 
